apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
spec:
  selector:
    app: frontend-proxy
  type: NodePort
  ports:
    - port: 8080           # Internal cluster port (optional)
      targetPort: 8080   # Your container's port
      nodePort: 30080    # External port (must be 30000-32767)
